variables:
    GIT_SUBMODULE_STRATEGY: recursive

ILH:debug:android:
    image: rabits/qt:5.9-android
    stage: build
    script:
        - mkdir build
        - cd build
        - ../compile_apk.sh
    tags:
        - c2d_docker

ILH:release:android:
    image: rabits/qt:5.9-android
    stage: build
    script:
        - mkdir build
        - cd build
        - ../compile_apk_release.sh
    only:
        - master
    tags:
        - c2d_docker
    artifacts:
        expire_in: 1 day
        when: on_success
        paths:
            - build/android//build/outputs/apk/android-debug.apk

ILH:release:android:deploy:
    image: appropriate/curl
    stage: deploy
    only:
        - master
    script:
        - curl https://upload.testfairy.com/api/upload -F api_key=$TESTFAIRY_API_KEY -F file=@build/android/build/outputs/apk/android-debug.apk
